# Generated by Django 3.0.5 on 2020-05-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_auto_20200509_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='lockerid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locker.Onboard'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lockerid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locker.Onboard'),
        ),
    ]
