# Generated by Django 3.0.5 on 2020-05-09 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_auto_20200509_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='country',
            field=models.CharField(default='India', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Numbers not allowed')]),
        ),
    ]
