# Generated by Django 3.0.5 on 2020-05-09 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_auto_20200509_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-z-A-Z0-9 ]+$', message='Numbers not allowed')]),
        ),
    ]
