# Generated by Django 3.0.5 on 2020-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_auto_20200509_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinglist',
            name='dist',
            field=models.FloatField(default=0.0),
        ),
    ]
