# Generated by Django 3.0.5 on 2020-05-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_auto_20200516_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
