# Generated by Django 3.0.5 on 2020-05-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0009_delete_coordinates'),
        ('locker', '0008_rankinglist_dist'),
    ]

    operations = [
    ]
