# Generated by Django 3.0.5 on 2020-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0010_merge_20200517_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinglist',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
