# Generated by Django 3.0.5 on 2020-04-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='addressfield',
        ),
    ]
