# Generated by Django 3.0.5 on 2020-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_addressfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='addressfield',
            field=models.CharField(default='jaypee', max_length=100),
            preserve_default=False,
        ),
    ]
