# Generated by Django 3.0.5 on 2020-05-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200423_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lattitude',
            field=models.FloatField(default=27.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(default=77.34),
            preserve_default=False,
        ),
    ]
