# Generated by Django 3.0.5 on 2020-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20200503_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lattitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
